### ISSUE TITLE
500 when creating survey at X1-XA95-57213D

### ISSUE THREAD

**Issue by eseidel** [SpaceTradersAPI/api-docs#51]
Times are in California time.  Ship #1 is the command ship.

I was expecting something else to go wrong, but it looks like the command ship was trying to create a survey at X1-XA95-57213D?

```
🛸#1 🛫 to X1-XA95-57213D ASTEROID_FIELD (00:00:43) spent 85 fuel
[WARN] 🛸#4 All systems connected to X1-DS14-05264X explored, jumping to furthest system, X1-Y64.
🛸#4 🥶 for 00:03:05
[WARN] 🛸#5 All systems connected to X1-UD78-72865Z explored, jumping to furthest system, X1-KF4.
🛸#5 🥶 for 00:03:00
⏱️  32s until 2023-05-27 20:30:29.915
Unhandled exception:
ApiException 500: {"error":{"code":500,"message":"Something unexpected went wrong! If you want to help you can file an issue here: https://github.com/SpaceTradersAPI/api-docs"}}
#0      FleetApi.createSurvey (package:space_traders_api/api/fleet_api.dart:332:7)
<asynchronous suspension>
#1      loadOrCreateSurveySetIfPossible (package:space_traders_cli/behavior/miner.dart:27:20)
<asynchronous suspension>
#2      advanceMiner (package:space_traders_cli/behavior/miner.dart:88:21)
<asynchronous suspension>
#3      logicLoop (package:space_traders_cli/logic.dart:119:25)
<asynchronous suspension>
#4      logic (package:space_traders_cli/logic.dart:201:7)
<asynchronous suspension>
#5      main (file:///C:/Users/micro/Documents/GitHub/space_traders/packages/space_traders_cli/bin/space_traders_cli.dart:35:3)
<asynchronous suspension>
```

**Comment by eseidel** [comment]
Hmm, it's repeating, investigating.

```
🛸#1 Surveying X1-XA95-57213D
Unhandled exception:
ApiException 500: {"error":{"code":500,"message":"Something unexpected went wrong! If you want to help you can file an issue here: https://github.com/SpaceTradersAPI/api-docs"}}
#0      FleetApi.createSurvey (package:space_traders_api/api/fleet_api.dart:332:7)
```

**Comment by eseidel** [comment]
`🛸#1 at X1-XA95-57213D - ASTEROID_FIELD - Stripped`

I suspect the "stripped" is the problem and the 500 is just a bad error?

**Comment by eseidel** [comment]
Hmm, but hq's system's asteroid field is stripped and it doesn't 500. 🤔

**Comment by space-admiral** [comment]
Thanks for reporting this! Did you find out if there is a specific action that always generates a 500 error? This was probably an intermittent error but I'm not sure.

**Comment by eseidel** [comment]
I've never seen it since.  I suspect it was just intermittent.  Mostly filed so you had the timestamps in case you wanted to compare your logs. Thanks!
